set nocompatible
set encoding=utf-8
"set number " Display line numbers on the left
"set numberwidth=3
set viminfo+=n~/.config/vim/viminfo
set confirm "Instead of failing a command because of unsaved changes, instead raise a dialogue asking if you wish to save changed files.
set clipboard+=unnamed " Allow copying from Vim
set selection=exclusive " Don't grab the gutter when selecting with the mouse in visual mode
set noswapfile " Avoid cruft
set backspace=indent,eol,start
set wildmenu " Enable the wildmenu
set wildmenu wildoptions=pum " Menu appears vertically
filetype plugin on " Added for Vimwiki

" Allow mouse in all modes, hopefully excluding line nums on yank
set mouse=a

let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin()
    " Initialize plugin system
    " - Automatically executes `filetype plugin indent on` and `syntax enable`.
    Plug 'dracula/vim', { 'as': 'dracula' }

    source ~/.vim/configs/ale.vim
    source ~/.vim/configs/airline.vim
    if executable('node')
        source ~/.vim/configs/coc.vim
    endif
    source ~/.vim/configs/commentary.vim
    source ~/.vim/configs/fugitive.vim
    source ~/.vim/configs/nerdtree.vim
    source ~/.vim/configs/signature.vim
    source ~/.vim/configs/surround.vim
    source ~/.vim/configs/vimwiki.vim

    if has('mac')
        source ~/.vim/configs/floaterm.vim
    endif

call plug#end()

source ~/.vim/configs/theme-tweaks.vim " Theme Content
source ~/.vim/configs/keymaps.vim " Custom Keymappings
source ~/.vim/configs/formatting.vim " Tabs, Spaces, All That...
source ~/.vim/configs/search-related.vim " Changes search functions and styles

" Source ~/.vim/vimrc.local if it exists (to allow machine-specific tweaks)
if filereadable($HOME . '/.vim/vimrc.local')
    source $HOME/.vim/vimrc.local
endif
